server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/microserver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid: 
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 1.0
security:
  basic:
    enabled: false
logging:
  level:
    root: INFO
    com.boyu.microserviceweb: DEBUG
feign: 
  okhttp: 
    enabled: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.boyu.microserviceweb.model
init-db: true
management:
  security:
    enabled: false
tm:
  manager:
    url: http://127.0.0.1:8899/tx/manager/
security:
  oauth2:
    resource:
      user-info-uri: http://microservice-api-gateway/user
      id: openid
    client:
      clientId: user-servicce
      clientSecret: 1234
      accessTokenUri: http://microservice-auth/uaa/oauth/token
      grant-type: client_credentials
      scope: server