server:
  port: 17601

spring:
  application:
    # 本服务注册到注册到服务器的名称, 这个名称就是后面调用服务时的服务标识符
    name: microservice-zipkin
    
  cloud:
    config:
      profile: dev
      label: master
      discovery:
        enabled: true
        service-id: microservice-config-server
      fail-fast: true
      retry:
        # 配置重试次数，默认为6
        max-attempts: 6
        # 间隔乘数，默认1.1
        multiplier: 1.1
        # 初始重试间隔时间，默认1000ms
        initial-interval: 1000
        # 最大间隔时间，默认2000ms
        max-interval: 2000
    # zipkin数据存储到mysql中
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/microserver?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: true
  sleuth:
        enabled: false
eureka:
  client:
    serviceUrl:
      # 服务器注册/获取服务器的zone
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
zipkin:
  collector:
    rabbitmq:
      addresses: localhost:5672
      password: guest
      username: guest
      queue: zipkin
  storage:
   type: mysql
