server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 1.0

logging:
  level:
    root: INFO
    org.hibernate: INFO
feign:
  hystrix:
    enabled: true