server:
  port: 8081
spring:
  application:
    name: microservice-web
  zipkin:
    base-url: http://localhost:9002
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    config:
      profile: dev
      label: master
      discovery:
        enabled: true
        service-id: microservice-config-server
      fail-fast: true
      retry:
        # 配置重试次数，默认为6
        max-attempts: 6
        # 间隔乘数，默认1.1
        multiplier: 1.1
        # 初始重试间隔时间，默认1000ms
        initial-interval: 1000
        # 最大间隔时间，默认2000ms
        max-interval: 2000
  rabbitmq:  
      host: localhost  
      port: 5672  
      username: guest  
      password: guest

logging:
  level:
    root: INFO
    org.hibernate: INFO
feign:
  hystrix:
    enabled: true
